# Generated by Django 4.1.3 on 2022-11-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "cinemaid",
                    models.IntegerField(
                        db_column="cinemaID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("district", models.CharField(blank=True, max_length=45, null=True)),
                ("city", models.CharField(blank=True, max_length=45, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "cinema",
            },
        ),
        migrations.CreateModel(
            name="CinemaHall",
            fields=[
                (
                    "cinema_hallid",
                    models.IntegerField(
                        db_column="cinema_hallID", primary_key=True, serialize=False
                    ),
                ),
                ("total_seats", models.IntegerField(blank=True, null=True)),
                (
                    "cinemaid",
                    models.ForeignKey(
                        blank=True,
                        db_column="cinemaID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.cinema",
                    ),
                ),
            ],
            options={
                "db_table": "cinema_hall",
            },
        ),
        migrations.CreateModel(
            name="CinemaSeat",
            fields=[
                (
                    "cinema_seatid",
                    models.IntegerField(
                        db_column="cinema_seatID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, db_column="Type", max_length=45, null=True
                    ),
                ),
                ("row_no", models.IntegerField(blank=True, null=True)),
                ("col_no", models.IntegerField(blank=True, null=True)),
                (
                    "cinema_hallid",
                    models.ForeignKey(
                        blank=True,
                        db_column="cinema_hallID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.cinemahall",
                    ),
                ),
            ],
            options={
                "db_table": "cinema_seat",
            },
        ),
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                (
                    "discount_couponid",
                    models.IntegerField(
                        db_column="discount_couponID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "discount_amount",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "discount_coupon",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "movieid",
                    models.IntegerField(
                        db_column="MovieID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "poster",
                    models.CharField(
                        blank=True, db_column="Poster", max_length=45, null=True
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, db_column="Genre", max_length=45, null=True
                    ),
                ),
                ("date", models.DateTimeField(blank=True, db_column="Date", null=True)),
                (
                    "actors",
                    models.CharField(
                        blank=True, db_column="Actors", max_length=45, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=45, null=True
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, db_column="Director", max_length=45, null=True
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, db_column="Duration", max_length=45, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, db_column="Language", max_length=45, null=True
                    ),
                ),
            ],
            options={
                "db_table": "movie",
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "showid",
                    models.IntegerField(
                        db_column="showID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "starttime",
                    models.CharField(
                        blank=True, db_column="startTime", max_length=45, null=True
                    ),
                ),
                (
                    "endtime",
                    models.CharField(
                        blank=True, db_column="endTime", max_length=45, null=True
                    ),
                ),
                (
                    "cinema_hallid",
                    models.ForeignKey(
                        db_column="cinema_hallID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.cinemahall",
                    ),
                ),
                (
                    "movieid",
                    models.ForeignKey(
                        db_column="MovieID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.movie",
                    ),
                ),
            ],
            options={
                "db_table": "show",
            },
        ),
        migrations.CreateModel(
            name="ShowSeat",
            fields=[
                (
                    "show_seatid",
                    models.IntegerField(
                        db_column="show_seatID", primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=45, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "show_seat",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_name", models.IntegerField(primary_key=True, serialize=False)),
                ("password", models.CharField(blank=True, max_length=45, null=True)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("email", models.CharField(blank=True, max_length=45, null=True)),
                ("phone", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticketid",
                    models.IntegerField(
                        db_column="ticketID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "show_seatid",
                    models.ForeignKey(
                        blank=True,
                        db_column="show_seatID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.showseat",
                    ),
                ),
                (
                    "showid",
                    models.ForeignKey(
                        blank=True,
                        db_column="showID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.show",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="userID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.user",
                    ),
                ),
            ],
            options={
                "db_table": "ticket",
            },
        ),
        migrations.AddField(
            model_name="showseat",
            name="bookingid",
            field=models.ForeignKey(
                blank=True,
                db_column="bookingID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cinemium.ticket",
            ),
        ),
        migrations.AddField(
            model_name="showseat",
            name="cinema_seatid",
            field=models.ForeignKey(
                blank=True,
                db_column="cinema_seatID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cinemium.cinemaseat",
            ),
        ),
        migrations.AddField(
            model_name="showseat",
            name="showid",
            field=models.ForeignKey(
                blank=True,
                db_column="showID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cinemium.show",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "paymentid",
                    models.IntegerField(
                        db_column="paymentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_date",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "discount_couponid",
                    models.ForeignKey(
                        blank=True,
                        db_column="discount_couponID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.discountcoupon",
                    ),
                ),
                (
                    "ticketid",
                    models.ForeignKey(
                        blank=True,
                        db_column="ticketID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemium.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
