# Generated by Django 4.1.1 on 2023-01-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinemaseat",
            name="ticket_id",
        ),
    ]
