# Generated by Django 4.1.4 on 2023-01-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaseat',
            name='cinema_seat_id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
