# Generated by Django 4.1.1 on 2023-01-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="cinema_id",
            new_name="cinema",
        ),
        migrations.RenameField(
            model_name="cinemaseat",
            old_name="cinema_hall_id",
            new_name="cinema_hall",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="cinema_hall_id",
            new_name="cinema_hall",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="movie_id",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="seat_id",
            new_name="seat",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="show_id",
            new_name="show",
        ),
    ]
