# Generated by Django 4.1.1 on 2022-12-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="about",
            field=models.CharField(
                blank=True, db_column="About", max_length=1024, null=True
            ),
        ),
    ]
