# Generated by Django 4.1.4 on 2023-01-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemium', '0002_alter_cinemaseat_cinema_seat_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cinemaseat',
            name='ticket_id_not_null',
        ),
    ]
