# Generated by Django 4.1.1 on 2023-01-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0002_remove_cinemaseat_ticket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="seats",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="cinemaseat",
            name="booked_shows",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
