# Generated by Django 4.1.1 on 2023-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0002_rename_cinema_id_cinemahall_cinema_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="seat",
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.ManyToManyField(to="cinemium.cinemaseat"),
        ),
    ]
