# Generated by Django 4.1.1 on 2022-12-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0002_movie_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
