# Generated by Django 4.1.1 on 2022-12-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0003_movie_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="about",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="score",
        ),
    ]
