# Generated by Django 4.1.1 on 2023-01-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0003_remove_ticket_seat_ticket_seat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="seat",
            new_name="seats",
        ),
    ]
