# Generated by Django 4.1.1 on 2023-01-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0003_ticket_seats_alter_cinemaseat_booked_shows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemaseat",
            name="booked_shows",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
