# Generated by Django 4.1.1 on 2023-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0004_alter_cinemaseat_booked_shows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemaseat",
            name="booked_shows",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
