# Generated by Django 4.1.1 on 2022-12-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0004_remove_movie_about_remove_movie_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="about",
            field=models.CharField(
                blank=True, db_column="About", max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="score",
            field=models.FloatField(
                blank=True, db_column="Score", default=None, null=True
            ),
        ),
    ]
