# Generated by Django 4.1.1 on 2023-01-01 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0004_rename_seat_ticket_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinemaseat",
            name="status",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="seats",
        ),
        migrations.AddField(
            model_name="cinemaseat",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cinemaseat",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="purchase_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="cinemaseat",
            constraint=models.CheckConstraint(
                check=models.Q(("is_booked", True), ("ticket_id__isnull", False)),
                name="ticket_id_not_null",
            ),
        ),
    ]
