# Generated by Django 4.1.1 on 2023-01-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0005_remove_cinemaseat_status_remove_ticket_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemaseat",
            name="cinema_seat_id",
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
