# Generated by Django 4.1.1 on 2023-01-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0005_alter_cinemaseat_booked_shows"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
