# Generated by Django 4.1.1 on 2022-12-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0005_movie_about_movie_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="intheatre",
            field=models.BooleanField(
                blank=True, db_column="InTheatre", default=None, null=True
            ),
        ),
    ]
