# Generated by Django 4.1.1 on 2023-01-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0006_alter_cinemaseat_cinema_seat_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cinemaseat",
            name="ticket_id_not_null",
        ),
    ]
