# Generated by Django 4.1.1 on 2022-12-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemium", "0007_alter_movie_intheatre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="intheatre",
            field=models.BooleanField(db_column="InTheatre", default=True),
        ),
    ]
