# Generated by Django 4.1.1 on 2022-12-27 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cinemium", "0008_alter_movie_intheatre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="userid",
        ),
        migrations.AddField(
            model_name="movie",
            name="age",
            field=models.IntegerField(db_column="Age", default=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
