# Generated by Django 4.1.4 on 2022-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemium', '0010_remove_movie_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaseat',
            name='cinema_seatid',
            field=models.CharField(db_column='cinema_seatID', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cinemaseat',
            name='col_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cinemaseat',
            name='row_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
