# Generated by Django 4.1.4 on 2022-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemium', '0011_alter_cinemaseat_cinema_seatid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaseat',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=45, null=True),
        ),
    ]
