# Generated by Django 4.1.4 on 2022-12-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemium', '0012_cinemaseat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemaseat',
            name='type',
        ),
    ]
